import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';
import JSZip from 'jszip';
import { format } from 'date-fns';
import { zhCN, enUS } from 'date-fns/locale';
import i18n from '@/i18n/config';
import type { Ledger, RenqingRecord } from '@shared/types';
import { EVENT_TYPES } from '@/constants';

// A4尺寸：210mm x 297mm，在96dpi下约为794px x 1123px
const A4_WIDTH = 794;
const A4_HEIGHT = 1123;
const RECORDS_PER_PAGE = 10;

// 国际化文本
interface i18nTexts {
  appName: string;
  received: string;
  given: string;
  records: string;
  recordPage: string;
  page: string;
  by: string;
  totalRecords: string;
  ledgerFile: string;
  cover: string;
  recordPageFile: string;
}

function geti18nTexts(): i18nTexts {
  const lang = i18n.language;
  if (lang === 'zh') {
    return {
      appName: '礼尚',
      received: '收到',
      given: '送出',
      records: '条记录',
      recordPage: '礼簿记录',
      page: '页 / 共',
      by: '由礼尚生成',
      totalRecords: '共',
      ledgerFile: '礼簿',
      cover: '封面',
      recordPageFile: '记录页'
    };
  } else {
    return {
      appName: 'Harmony Ledger',
      received: 'Received',
      given: 'Given',
      records: 'records',
      recordPage: 'Records',
      page: 'Page / Total',
      by: 'Generated by Harmony Ledger',
      totalRecords: 'Total',
      ledgerFile: 'Ledger',
      cover: 'Cover',
      recordPageFile: 'Record_Page'
    };
  }
}

// 创建礼簿封面HTML
function createCoverHTML(ledger: Ledger, records: RenqingRecord[]): string {
  const texts = geti18nTexts();
  const currentLocale = i18n.language === 'zh' ? zhCN : enUS;
  const dateStr = format(ledger.date, i18n.language === 'zh' ? 'yyyy年MM月dd日' : 'MMM dd, yyyy', { locale: currentLocale });

  return `
    <div style="
      width: ${A4_WIDTH}px;
      height: ${A4_HEIGHT}px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      color: white;
      font-family: 'Microsoft YaHei', 'PingFang SC', sans-serif;
      position: relative;
      overflow: hidden;
    ">
      <div style="
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        opacity: 0.3;
      "></div>

      <div style="text-align: center; z-index: 1; position: relative;">
        <h1 style="
          font-size: 48px;
          font-weight: bold;
          margin-bottom: 20px;
          text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        ">${texts.appName}</h1>

        <h2 style="
          font-size: 36px;
          font-weight: bold;
          margin-bottom: 30px;
          text-shadow: 1px 1px 2px rgba(0,0,0,0.3);
        ">${ledger.title}</h2>

        <div style="
          font-size: 24px;
          margin-bottom: 40px;
          opacity: 0.9;
        ">${dateStr}</div>

        <div style="
          display: flex;
          gap: 60px;
          margin-bottom: 40px;
        ">
          <div style="text-align: center;">
            <div style="font-size: 18px; opacity: 0.8; margin-bottom: 8px;">${texts.received}</div>
            <div style="font-size: 32px; font-weight: bold;">¥${ledger.totalReceived.toLocaleString()}</div>
          </div>
          <div style="text-align: center;">
            <div style="font-size: 18px; opacity: 0.8; margin-bottom: 8px;">${texts.given}</div>
            <div style="font-size: 32px; font-weight: bold;">¥${ledger.totalGiven.toLocaleString()}</div>
          </div>
        </div>

        <div style="
          font-size: 16px;
          opacity: 0.7;
          border-top: 1px solid rgba(255,255,255,0.3);
          padding-top: 20px;
        ">
          ${texts.totalRecords} ${records.length} ${texts.records}
        </div>
      </div>
    </div>
  `;
}

// 创建记录页面HTML
function createRecordPageHTML(records: RenqingRecord[], pageIndex: number, totalPages: number): string {
  const texts = geti18nTexts();
  const startIndex = pageIndex * RECORDS_PER_PAGE;
  const endIndex = Math.min(startIndex + RECORDS_PER_PAGE, records.length);
  const pageRecords = records.slice(startIndex, endIndex);

  const recordsHTML = pageRecords.map((record, index) => {
    const eventTypeLabel = EVENT_TYPES.find(et => et.value === record.eventType)?.label || record.eventType;
    const isReceive = record.type === 'receive';

    return `
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px 30px;
        border-bottom: 1px solid #f0f0f0;
        background: ${index % 2 === 0 ? '#ffffff' : '#fafafa'};
      ">
        <div style="flex: 1;">
          <div style="
            font-size: 18px;
            font-weight: bold;
            color: #333;
            margin-bottom: 4px;
          ">${record.personName}</div>
          <div style="
            font-size: 12px;
            color: #666;
          ">${eventTypeLabel}${record.description ? ` • ${record.description}` : ''}</div>
        </div>
        <div style="
          font-size: 20px;
          font-weight: bold;
          color: ${isReceive ? '#10b981' : '#ef4444'};
          text-align: right;
        ">
          ${isReceive ? '+' : '-'}¥${record.amount.toLocaleString()}
        </div>
      </div>
    `;
  }).join('');

  const pageNum = i18n.language === 'zh' 
    ? `${texts.page} ${pageIndex + 1} ${totalPages}` 
    : `${texts.page} ${pageIndex + 1} / ${totalPages}`;

  return `
    <div style="
      width: ${A4_WIDTH}px;
      height: ${A4_HEIGHT}px;
      background: white;
      display: flex;
      flex-direction: column;
      font-family: 'Microsoft YaHei', 'PingFang SC', sans-serif;
      position: relative;
    ">
      <div style="
        padding: 30px;
        border-bottom: 2px solid #e5e7eb;
        background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
      ">
        <h3 style="
          font-size: 24px;
          font-weight: bold;
          color: #374151;
          margin: 0;
        ">${texts.recordPage}</h3>
        <div style="
          font-size: 14px;
          color: #6b7280;
          margin-top: 4px;
        ">${pageNum}</div>
      </div>

      <div style="flex: 1; display: flex; flex-direction: column;">
        ${recordsHTML}
      </div>

      <div style="
        padding: 20px 30px;
        border-top: 1px solid #e5e7eb;
        background: #f9fafb;
        font-size: 12px;
        color: #6b7280;
        text-align: center;
      ">
        ${pageNum} • ${texts.by}
      </div>
    </div>
  `;
}

// 创建离屏渲染容器
function createOffscreenContainer(): { container: HTMLElement; cleanup: () => void } {
  const container = document.createElement('div');
  // 修复点1：用透明度隐藏而非移出视口
  Object.assign(container.style, {
    width: `${A4_WIDTH}px`,
    height: `${A4_HEIGHT}px`,
    background: 'white',
  });
  document.body.appendChild(container);

  const cleanup = () => {
    container.remove(); // 现代 API 更安全
  };

  return { container, cleanup };
}

// 将HTML转换为图片
async function htmlToImage(html: string): Promise<string> {
  const { container, cleanup } = createOffscreenContainer();
  try {
    container.innerHTML = html;

    await document.fonts.ready;

    // 等待字体加载
    await new Promise(resolve => setTimeout(resolve, 100));
    const dataUrl = await toPng(container, {
      width: A4_WIDTH,
      height: A4_HEIGHT,
      quality: 1.0,
      pixelRatio: 2,
      backgroundColor: '#ffffff',
      style: { transform: 'none !important' }
    });

    return dataUrl;
  } catch (error) {
    console.error('HTML转图片失败:', error);
    throw new Error('生成图片失败');
  } finally {
    cleanup();
  }
}

/**
 * 通用文件下载函数（支持 Base64、ArrayBuffer、Blob 三种输入）
 * 
 * @param data - 文件数据 (支持完整 base64 URL / 纯 base64 字符串 / ArrayBuffer / Blob)
 * @param filename - 下载的文件名（需带扩展名，如 "image.png"）
 * @param mimeType - 可选 MIME 类型（当传入 Blob 时会优先使用其自带 type）
 */
function downloadFile(
  data: string | ArrayBuffer | Blob,
  filename: string,
  mimeType?: string
) {
  // 1️⃣ 处理 Blob 输入（核心修复点）
  if (data instanceof Blob) {
    // 优先使用 Blob 自带的 MIME type，除非用户强制指定新类型
    const finalMimeType = mimeType || data.type || "application/octet-stream";

    // 如果用户指定了不同 MIME type，创建新 Blob
    const finalBlob = mimeType && mimeType !== data.type
      ? new Blob([data], { type: mimeType })
      : data;

    // 2️⃣ 标准下载流程（复用逻辑）
    const url = URL.createObjectURL(finalBlob);
    triggerDownload(url, filename);
    return;
  }

  // 2️⃣ 处理 ArrayBuffer 输入
  if (data instanceof ArrayBuffer) {
    const blob = new Blob([data], {
      type: mimeType || "application/octet-stream"
    });
    const url = URL.createObjectURL(blob);
    triggerDownload(url, filename);
    return;
  }

  // 3️⃣ 处理字符串输入（Base64 或纯文本）
  if (typeof data === "string") {
    // 情况A：完整 base64 URL (data:image/png;base64,...)
    if (data.startsWith("data:")) {
      const [meta, base64] = data.split(",");
      const detectedType = mimeType || meta.match(/:(.*?);/)?.[1] || "application/octet-stream";

      // 解码 base64 为二进制
      const binary = atob(base64);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
      }

      const blob = new Blob([bytes], { type: detectedType });
      const url = URL.createObjectURL(blob);
      triggerDownload(url, filename);
      return;
    }

    // 情况B：纯 base64 字符串（无 data: 前缀）
    if (mimeType) {
      const binary = atob(data);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
      }

      const blob = new Blob([bytes], { type: mimeType });
      const url = URL.createObjectURL(blob);
      triggerDownload(url, filename);
      return;
    }

    // 情况C：纯文本（fallback）
    const blob = new Blob([data], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    triggerDownload(url, filename);
    return;
  }

  // ❌ 无效输入类型
  throw new Error("Unsupported data type. Must be string, ArrayBuffer, or Blob.");
}

// 🔁 抽离重复的下载逻辑
function triggerDownload(url: string, filename: string) {
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// 导出为单图片（竖向拼接）
export async function exportLedgerAsSingleImage(ledger: Ledger, records: RenqingRecord[]): Promise<void> {
  try {
    const images: string[] = [];

    // 生成封面
    const coverHTML = createCoverHTML(ledger, records);
    const coverImage = await htmlToImage(coverHTML);
    images.push(coverImage);

    // 计算需要的页数
    const totalPages = Math.ceil(records.length / RECORDS_PER_PAGE);

    // 生成记录页面
    for (let i = 0; i < totalPages; i++) {
      const pageHTML = createRecordPageHTML(records, i, totalPages);
      const pageImage = await htmlToImage(pageHTML);
      images.push(pageImage);
    }

    // 创建拼接容器
    const { container, cleanup } = createOffscreenContainer();
    container.style.height = `${A4_HEIGHT * images.length}px`;
    container.style.display = 'flex';
    container.style.flexDirection = 'column';

    // 添加所有图片
    for (const imageData of images) {
      const img = document.createElement('img');
      img.src = imageData;
      img.style.width = '100%';
      img.style.height = `${A4_HEIGHT}px`;
      img.style.objectFit = 'contain';
      container.appendChild(img);
    }

    // 等待图片加载
    await new Promise(resolve => {
      const imgs = container.querySelectorAll('img');
      let loaded = 0;
      imgs.forEach(img => {
        img.onload = () => {
          loaded++;
          if (loaded === imgs.length) resolve(void 0);
        };
      });
    });

    // 生成最终图片
    const finalImage = await toPng(container, {
      width: A4_WIDTH,
      height: A4_HEIGHT * images.length,
      quality: 1.0,
      pixelRatio: 1,
      backgroundColor: '#ffffff',
      style: { transform: 'none !important' }
    });

    cleanup();

    // 下载图片
    const texts = geti18nTexts();
    const filename = `${ledger.title}_${texts.ledgerFile}_${format(new Date(), 'yyyyMMdd')}.png`;
    downloadFile(finalImage, filename, 'image/png');
  } catch (error) {
    console.error('Export single image failed:', error);
    throw new Error('Export failed, please try again');
  }
}

// 导出为多图片压缩包
export async function exportLedgerAsImageZip(ledger: Ledger, records: RenqingRecord[]): Promise<void> {
  try {
    const zip = new JSZip();
    const images: { name: string; data: string }[] = [];

    // 生成封面
    const coverHTML = createCoverHTML(ledger, records);
    const coverImage = await htmlToImage(coverHTML);
    const texts = geti18nTexts();
    images.push({ name: `${texts.cover}.png`, data: coverImage });

    // 计算需要的页数
    const totalPages = Math.ceil(records.length / RECORDS_PER_PAGE);

    // 生成记录页面
    for (let i = 0; i < totalPages; i++) {
      const pageHTML = createRecordPageHTML(records, i, totalPages);
      const pageImage = await htmlToImage(pageHTML);
      images.push({ name: `${texts.recordPageFile}_${i + 1}.png`, data: pageImage });
    }

    // 添加图片到压缩包
    for (const image of images) {
      // 将base64转换为blob
      const response = await fetch(image.data);
      const blob = await response.blob();
      zip.file(image.name, blob);
    }

    // 生成并下载压缩包
    const zipBlob = await zip.generateAsync({ type: 'blob' });
    const filename = `${ledger.title}_礼簿_${format(new Date(), 'yyyyMMdd')}.zip`;
    downloadFile(zipBlob, filename, 'application/zip');

  } catch (error) {
    console.error('导出压缩包失败:', error);
    throw new Error('导出失败，请重试');
  }
}

// 导出为PDF
export async function exportLedgerAsPDF(ledger: Ledger, records: RenqingRecord[]): Promise<void> {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // 生成封面图片
    const coverHTML = createCoverHTML(ledger, records);
    const coverImage = await htmlToImage(coverHTML);

    // 添加封面到PDF
    pdf.addImage(coverImage, 'PNG', 0, 0, 210, 297);

    // 计算需要的页数
    const totalPages = Math.ceil(records.length / RECORDS_PER_PAGE);

    // 生成记录页面
    for (let i = 0; i < totalPages; i++) {
      pdf.addPage();
      const pageHTML = createRecordPageHTML(records, i, totalPages);
      const pageImage = await htmlToImage(pageHTML);
      pdf.addImage(pageImage, 'PNG', 0, 0, 210, 297);
    }

    // 下载PDF
    const filename = `${ledger.title}_礼簿_${format(new Date(), 'yyyyMMdd')}.pdf`;
    pdf.save(filename);

  } catch (error) {
    console.error('导出PDF失败:', error);
    throw new Error('导出失败，请重试');
  }
}